### ISSUE TITLE
mongos

### ISSUE THREAD

**Issue by stephenhuey** [seanemmer/mongoose-seed#14]
Been using this for a while on my local machine.  Just noticed there's no way to pass options to mongoose.connect - any desire to support that?  I'm unable to seed a mongos.  For example, my Express app can connect by using these options: 

mongooseOptions = {
  mongos: {
    poolSize: 5,
    reconnectTries: 1000  
  }
}

But there's no way for me to pass these options to mongoose-seed.

**Comment by seanemmer** [comment]
Good idea - feel free to submit a PR for this

**Comment by stephenhuey** [comment]
I did:

https://github.com/seanemmer/mongoose-seed/pull/16

**Comment by seanemmer** [comment]
Ok, PR accepted - I'll test this out and add to NPM over the weekend
