### ISSUE TITLE
Ref other models

### ISSUE THREAD

**Issue by FrenchBully** [seanemmer/mongoose-seed#17]
Does this currently support referencing other model schemas within a model?

**Comment by seanemmer** [comment]
This should work as long as you lode those models as well.

**Comment by rubenvde** [comment]
Can you please explain this for me? 
I followed the readme and my `var data` array is looking something like this:
```json{
  'model': 'Section',
  'documents': [
  {
        "title": "Bla",
  },
  ]
},
{
  'model': 'Project',
  'documents': [
    {
      'title': 'Test project',
      'sections': [],
    },
  ]
}
```

How is it possible to insert the first 'Section' to the 'Project' model where it's referenced in the sections attribute?

I'm sad to see that there isn't any test written using the "ref" attribute.
