### ISSUE TITLE
Push latest version

### ISSUE THREAD

**Issue by ohcibi** [seanemmer/mongoose-seed#18]
On npm there is version `0.3.2` released but in github is only `0.1.5`. Could you push the latest version please?

**Comment by seanemmer** [comment]
Thanks for flagging, pushed!

**Comment by ohcibi** [comment]
@seanemmer 👺

**Comment by seanemmer** [comment]
@ohcibi 0.5 here - is it mislabeled somewhere else?

https://github.com/seanemmer/mongoose-seed/blob/master/package.json

**Comment by ohcibi** [comment]
🤦‍♂️ . I thought i cloned it but I must have ignored the error that the directory already existed and it was checked out from my last pull request. Luckily my latest PR, which based on that was still applicable 8-))
