### ISSUE TITLE
remove `node_modules` directory from repo

### ISSUE THREAD

**Issue by tjaartvdwalt** [seanemmer/mongoose-seed#2]
Is there a reason you have committed the `node_modules` directory to your repo?

Best practice is to add that directory to `.gitignore` and let npm install the dependencies.

**Comment by agepath** [comment]
Great suggestion @tjaartvdwalt 

Glad you've discovered the repo - let me know if you have other ideas on how to improve it!

**Comment by seanemmer** [comment]
Great suggestion @tjaartvdwalt 

Glad you've discovered the repo - let me know if you have other ideas on how to improve it!

**Comment by tjaartvdwalt** [comment]
Great. This seems like a really nice project.
