### ISSUE TITLE
No info output

### ISSUE THREAD

**Issue by rhorber** [seanemmer/mongoose-seed#26]
When using `mongoose-seed` for integration tests, we get a lot of output from `mongoose-seed` which is not relevant for us at this time.

How about adding an option (or so) to deactivate `console.log` calls?

If you like, I could create a PR with a proposal.

**Comment by agepath** [comment]
Great idea - happy to look at a PR

**Comment by seanemmer** [comment]
Great idea - happy to look at a PR
