### ISSUE TITLE
Add callback to populateModels in order to execute mongoose-seed from a grunt task

### ISSUE THREAD

**Issue by andresgariglio** [seanemmer/mongoose-seed#5]
It'd be really helpful to add a callback to populateModels, in order to execute mongoose-seed from a grunt task, in an async way, passing done as argument/callback.

**Comment by agepath** [comment]
Great suggestion @andresgariglio - just updated the repo and npm package!

**Comment by seanemmer** [comment]
Great suggestion @andresgariglio - just updated the repo and npm package

**Comment by teckays** [comment]
You also should fail safe call this calback call: [here](https://github.com/seanemmer/mongoose-seed/blob/master/index.js#L147) in case it's not provided
